### ISSUE TITLE
Can no longer download pack thumbnails

### ISSUE THREAD

**Issue by seth-rah** [iomintz/Adhesive#14]
When attempting to convert a telegram pack to signal, the folllowing error occurs:
```
Traceback (most recent call last):
  File "/home/bots/adhesive/adhesive/telegram_bot.py", line 41, in handler
    await f(event)
  File "/home/bots/adhesive/adhesive/telegram_bot.py", line 63, in convert
    async for is_link, response in convert_link_interactive(
  File "/home/bots/adhesive/adhesive/glue.py", line 32, in convert_link_interactive
    async for is_link, message in convert_pack_interactive(db, tg_client, stickers_client, converter, *pack_info):
  File "/home/bots/adhesive/adhesive/glue.py", line 50, in convert_pack_interactive
    async for response in converter(db, tg_client, stickers_client, *pack_info):
  File "/home/bots/adhesive/adhesive/glue.py", line 126, in convert_to_signal
    await download_tg_cover(tg_client, signal_pack, tg_pack)
  File "/home/bots/adhesive/adhesive/glue.py", line 162, in download_tg_cover
    volume_id=thumb.location.volume_id,
AttributeError: 'PhotoSize' object has no attribute 'location'
```

**Comment by ioistired** [comment]
Hi @seth-rah, I updated the issue with details from the error code that you posted. I'll take a look when I can.
