### ISSUE TITLE
Error when sending stickers to Telegram Bot: TypeError: __init__() missing 1 required positional argument: 'hash'

### ISSUE THREAD

**Issue by Paschwuerfler** [iomintz/Adhesive#26]
When sending a sticker to the telegram bot, the bot errors out. 
This is the console log: 
```
ERROR:adhesive.telegram_bot:Unhandled exception in convert_sticker (18322785141090698656)
Traceback (most recent call last):
  File "/home/paul/Adhesive/adhesive/telegram_bot.py", line 41, in handler
    await f(event)
  File "/home/paul/Adhesive/adhesive/telegram_bot.py", line 78, in wrapped_handler
    return await handler(event)
  File "/home/paul/Adhesive/adhesive/telegram_bot.py", line 85, in convert_sticker
    async for is_link, response in convert_pack_interactive(
  File "/home/paul/Adhesive/adhesive/glue.py", line 50, in convert_pack_interactive
    async for response in converter(db, tg_client, stickers_client, *pack_info):
  File "/home/paul/Adhesive/adhesive/glue.py", line 100, in convert_to_signal
    tg_pack = await tg_client(tl.functions.messages.GetStickerSetRequest(input_sticker_set))
TypeError: __init__() missing 1 required positional argument: 'hash'
```

**Comment by ioistired** [comment]
Fixed by pinning Telethon to an older version. Will push soon.
