### ISSUE TITLE
"internal error" importing `randompacc`

### ISSUE THREAD

**Issue by deobald** [iomintz/Adhesive#30]
While trying to import a sticker pack (`randompacc`), an internal error is returned with no other information. I've tried the sticker pack URL and posting an individual sticker, as below:

> https://t.me/addstickers/randompacc

```
An internal error occurred while trying to run that command. 
Hey if you see the owner, give them this code okay? 
12276346398779449083
```

> Sticker

```
An internal error occurred while trying to run that command. 
Hey if you see the owner, give them this code okay? 
14181626151827031578
```

HTH!

**Comment by Zerogoki00** [comment]
Same problem 

```
An internal error occurred while trying to run that command. Hey if you see the owner, give them this code okay? 6121515369133027630
```

**Comment by Zerogoki00** [comment]
Still same problem
```
An internal error occurred while trying to run that command. Hey if you see the owner, give them this code okay? 12424132357514355347
```

**Comment by ioistired** [comment]
This is the error I'm getting

```
INFO:httpx:HTTP Request: GET https://chat.signal.org/v1/sticker/pack/form/120 "HTTP/1.1 401 Unauthorized"
ERROR:adhesive.telegram_bot:Unhandled exception in convert (7801438790048528376)
Traceback (most recent call last):
  File "/opt/adhesive/adhesive/telegram_bot.py", line 41, in handler
    await f(event)
  File "/opt/adhesive/adhesive/telegram_bot.py", line 63, in convert
    async for is_link, response in convert_link_interactive(
    ...<2 lines>...
        await maybe_enter_convo(event, is_link, response)
  File "/opt/adhesive/adhesive/glue.py", line 32, in convert_link_interactive
    async for is_link, message in convert_pack_interactive(db, tg_client, stickers_client, converter, *pack_info):
        logger.debug('convert_link_interactive: %r', message)
        yield is_link, message
  File "/opt/adhesive/adhesive/glue.py", line 50, in convert_pack_interactive
    async for response in converter(db, tg_client, stickers_client, *pack_info):
    ...<4 lines>...
            yield response
  File "/opt/adhesive/adhesive/glue.py", line 132, in convert_to_signal
    pack_info = await stickers_client.upload_pack(signal_pack)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/adhesive/adhesive/stickers_client.py", line 59, in upload_pack
    return await uploader.upload_pack(self.http, pack, account.username, account.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adhesive/.venv/lib/python3.13/site-packages/signalstickers_client/classes/uploader.py", line 30, in upload_pack
    raise Unauthorized(register_resp, "Invalid authentication")
signalstickers_client.errors.Unauthorized: 401: Invalid authentication
```

I will look into it.
