### ISSUE TITLE
→Telegram: handle invalid emojis

### ISSUE THREAD

**Issue by ioistired** [iomintz/Adhesive#7]
converting this pack:

https://signal.art/addstickers/#pack_id=e76a010259fc6011059fee999946387f&pack_key=a517923068c864f320c4c3fff07f157562050518a92c8c0bab0b4b58a1d6ad42

gives this error:

```
ERROR:adhesive.signal_bot:Unhandled exception in convert_sticker (2416445211293941633)
Traceback (most recent call last):
  File "/home/bots/adhesive/adhesive/signal_bot.py", line 21, in handler
    await f(ctx)
  File "/home/bots/adhesive/adhesive/signal_bot.py", line 64, in convert_sticker
    async for _, response in convert_pack_interactive(
  File "/home/bots/adhesive/adhesive/glue.py", line 48, in convert_pack_interactive
    async for response in converter(db, tg_client, stickers_client, *pack_info):
  File "/home/bots/adhesive/adhesive/glue.py", line 240, in convert_to_telegram
    tg_pack = await tg_client(tl.functions.stickers.CreateStickerSetRequest(
  File "/home/bots/adhesive/.venv/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/bots/adhesive/.venv/lib/python3.8/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.StickerEmojiInvalidError: Sticker emoji invalid (caused by CreateStickerSetRequest)
```

**Comment by ioistired** [comment]
These are the emoji in that pack. I either need to write a script which tries to make one sticker pack per emoji, or find out which exact stickers Telegram supports.
```
🌳
🤝
🤚
🌹
☮️
🕊️
🌈
😷
🤧
💡
♻️
🌐
⏳
😵
☀️
♦️
💚
🌱
🌾
🙋🏿
🐰
🐇
🐁
🐾
✊🏽
💖
🔺
🏳️‍🌈
⚧️
🐙
🎗️
🎀
🙎‍♀️
🧕
😻
👒
🦹‍♀️
✊🏿
💪🏿
⚖️
🦸🏿‍♂️
👬🏿
🪶
🚲
🚴
🚴‍♂️
❤️
💜
🪢
👋
👁️‍🗨️
🏠
🏡
🌺
⭐
🌟
⏸️
✖️
❌
⚡
🚮
🤛🏿
↙️
🔚
🚩
🏴
🚫
⚔️
🅰️
🏷️
💀
☠️
🚀
💥
✨
🐚
🛠️
📜
📑
⚫
🪧
📦
📄
📋
🔖
🏳️
🗂️
🪵
🎌
👕
👔
👚
```
